add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})
set_encodings("utf-8")
set_languages("c++17")

target("VirtualDesktopSwitcher")
    set_kind("binary")
    set_optimize("smallest")
    add_files("src/*.cpp", "src/icon.rc")
    add_syslinks("shell32", "shlwapi", "user32", "gdi32", "advapi32")
    add_ldflags("/SUBSYSTEM:WINDOWS")