add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})
set_encodings("utf-8")
set_languages("c++17")
set_version("1.0.2")

target("VirtualDesktopSwitcher")
    set_kind("binary")
    set_optimize("smallest")
    add_files("src/*.cpp", "src/icon.rc")
    add_includedirs("src", "libs")
    add_syslinks("shell32", "shlwapi", "user32", "gdi32", "advapi32", "comctl32", "comdlg32")
    add_ldflags("/SUBSYSTEM:WINDOWS")

    on_load(function (target)
        target:add("defines", string.format([[APP_VERSION="%s"]], target:version()))
    end)
